name: test build arduino-builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: make build
