name: Docker Image CI

on:
  release:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/arduino-builder:latest
    - name: Push the Docker image
      run: >
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/arduino-builder:latest
