name: Docker Image CI

on:
  release:
    types: [published]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/arduino-builder:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/arduino-builder:${{ steps.get_version.outputs.VERSION }}
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/arduino-builder:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/arduino-builder:${{ steps.get_version.outputs.VERSION }}
